### ISSUE TITLE
segfault on getParent call

### ISSUE THREAD

**Issue by remicollet** [krakjoe/ui#15]
```
class ExtensionCombo extends Combo {

	protected function onSelected() {
		var_dump($this->getParent());
        }
}

```

I'm trying to get a backtrace... but no luck for now... (no display when run in gdb)

**Comment by krakjoe** [comment]
That's a flaw in getParent, I think you may have to know the class of the parent.

**Comment by krakjoe** [comment]
Added protected parent property on Controls, just like the controls property of Form or whatever, this should not be manipulated directly.

**Comment by remicollet** [comment]
I confirm, fix is OK.

Thanks.
