### ISSUE TITLE
UI\Control::destroy() segfault

### ISSUE THREAD

**Issue by remicollet** [krakjoe/ui#19]
When trying to destroy a used control:
```
[libui] /dev/shm/BUILD/libui-f56411fde197481c00ad950e1a545452d47efa55/common/control.c:76:uiFreeControl() You have a bug: You cannot destroy a uiControl while it still has a parent. (control: 0x55e1a8db1e20)
Trace/breakpoint trap (core dumped)
```

**Comment by krakjoe** [comment]
The fault is caused by libui on purpose, it triggers a breakpoint in a debugger.

**Comment by remicollet** [comment]
Yes, I understand this.
Not critical, as ui is CLI only, but perhaps could be better to avoid dying and raise an exception instead ?
