### ISSUE TITLE
Repeatable: causes crash with ToDoist on macOS Sierra

### ISSUE THREAD

**Issue by phpcodemonkey** [krakjoe/ui#5]
In initial testing with php-ui, there's a repeatable issue observable when any php-ui window is first brought into focus - it causes ToDoist application to generate an "Internal Error - An uncaught exception was raised" with a stack trace, ToDoist can "Continue", however, I'm never sure that's a wise move. This issue presents whether ToDoist was running before the php process or not, they just both have to be running and the php-ui window gain focus (click or alt-tab display the problem, e.g. simply gaining focus).

The source of this could be upstream in libui itself of course or ToDoist (a usually stable app v6.3.16 (Build 10640)), however, I would have thought things shouldn't be crossing over like this.

Example ToDoist stack trace at https://gist.github.com/phpcodemonkey/c645758b0296860fef0daed2db010f32

**Comment by krakjoe** [comment]
Finding out if this is an upstream problem, it really sounds like one ...

**Comment by andlabs** [comment]
What is "ToDoist application"?

**Comment by krakjoe** [comment]
I assume this: https://en.todoist.com/

**Comment by phpcodemonkey** [comment]
Yes that's right, specifically, the Mac version https://en.todoist.com/mac

**Comment by andlabs** [comment]
And it is running as a separate process?

**Comment by phpcodemonkey** [comment]
I would hope/assume so, given that it's an App Store app!

**Comment by andlabs** [comment]
Definitely curious. Can you see if it happens with regular libui (not PHP)?

**Comment by phpcodemonkey** [comment]
@andlabs Yes, just ran make examples in libgui, then ran controlgallery, cpp-multithread & histogram with ToDoist - exact same behaviour. So that confirms it's related to upstream libgui after all.

**Comment by phpcodemonkey** [comment]
For reference, this compiled is with the latest master of libgui.

**Comment by andlabs** [comment]
It's either libui or todoist, and I'm hoping it's the former...

**Comment by andlabs** [comment]
Actually wait, how are you running the libui programs? Are you running them through Finder, or through Xcode, or through the command line? Are they a .app bundle, or a bare executable? I might have an idea as to what's going on, but I'm not sure whether libui is breaking a rule or Todoist is making an assumption.

And does Todoist have a feature where it watches for apps being launched?

**Comment by andlabs** [comment]
Actually forget that, whatever the answer is, the bug is actually in Todoist:

https://developer.apple.com/reference/appkit/nsrunningapplication/1535500-bundleurl?language=objc

The `bundleURL` property of a NSRunningApplication is allowed to be `nil`. Todoist is assuming it can never be `nil`, and is thus crashing because libui programs that are not run in .app bundles have no bundle URL.

So this will have to be reported to them.

**Comment by phpcodemonkey** [comment]
Ok thanks, at least that's a good find! For completeness, I was running libui apps from the command line as bare executables.

**Comment by andlabs** [comment]
Yep, so that lines up with what I found. Thanks!

**Comment by krakjoe** [comment]
I'm going to close the bug because there is nothing that I, or @andlabs can do now.

@phpcodemonkey feel free to (please do) update this thread with whatever you find when you report upstream.

**Comment by phpcodemonkey** [comment]
Thanks @krakjoe @andlabs! Reported upstream, fingers crossed!

**Comment by phpcodemonkey** [comment]
From ToDoist:
> Our developer believes that this is an issue that might have been addressed in version 6.3.17. Can you please let us know if the issue still persists for you even with that version?

And it is solved :)

**Comment by andlabs** [comment]
Cool :D

**Comment by andlabs** [comment]
Cool :D
