### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dmvdbrugge** [krakjoe/ui#50]
I was stoked to learn about this project. I had problems getting it to work, but once I managed, I started using it. I built a library around it. Found weird things, created issues.

Then I discovered that the latest working build is almost 2 years old, and only 3 commits after that. Is there any chance this project will be picked up again?

Libui still sees active development, with the latest commits being only 3 weeks old.

**Comment by ghostjat** [comment]
@krakjoe, is the project dead? :(
at least there must 1 fully supported gui extension in php like other languages have.

**Comment by andersonunsonst** [comment]
ping @krakjoe  ?

**Comment by dmvdbrugge** [comment]
Closing to clean up my stuff and this repo is dead anyway.
