### ISSUE TITLE
Rewrite events ("on..." methods)

### ISSUE THREAD

**Issue by WinterSilence** [krakjoe/ui#60]
Set event as callback:
~~~
class UI\Control
{
	protected $on = [];

	protected function on(string $event, callable $callback): self
	{
		if (!($callback instanceof \Closure)) {
			$callback = \Closure::fromCallable($callback);
		}
		$this->on[strtolower($event)] = $callback;
		return $this;
	}
}

class UI\Controls\Button extends UI\Control
{
	public function onClick(callable $callback): self
	{
		return $this->on('click', $callback);
	}
}
~~~

**Comment by dmvdbrugge** [comment]
Shameless plug for my library: https://github.com/dmvdbrugge/dynamic-components 😉

**Comment by WinterSilence** [comment]
@dmvdbrugge your library have minuses:  
1. PHP version  `>=7.1`, `ui` extension `>=7.0`
2. No interface defines setter/getter for events
3. No class extends `UI\Controls` and implemens interface by `2.`
4. Logic errors: if callable variable sets as array `['class', 'method']` then `$onChange($this);` not work, If you pass `$this` as callback argument then protected methods/properties not be available.

**Comment by dmvdbrugge** [comment]
1. Php 7.0 is no longer supported  (and it seems neither is this extension anyway), I saw no need for it. Upgrade to 7.1 is dead-easy, especially for desktop (why else have this extension). You may call this a minus, I think it's promoting not lagging behind.
2. What do you need an interface for here? They're extensions of the controls.
3. They **all** are extending their respective `UI\Controls`
4. I think you are misreading what it does and should do, and how it's supposed to be used. What makes you think you should have access to protected methods of the control?

**Comment by WinterSilence** [comment]
2. For adds common setter/getter for event callbacks, current  `UI\Controls` dont have this methods.
3. not all, see `UI\Menu`, `UI\MenuItem`
4.
~~~
$btn = new DynamicComponents\Controls\Button('Ok', [new \Foo\EventManager, 'click']);
// trigger `click`: error at method `onClick`
~~~

**Comment by dmvdbrugge** [comment]
It's not really fair to say my lib has issues, and then point out things the extension itself "does wrong" (in your opinion) 😉

Re 4: any error there is caused by whatever you do in that click, because this:
```php
class EventManager
{
    public function click(DynamicComponents\Controls\Button $ctrl)
    {
        echo $this->getMessage($ctrl), PHP_EOL;
    }

    private function getMessage(DynamicComponents\Controls\Button $ctrl)
    {
        return "Clicked {$ctrl->getText()}";
    }
}

$btn = new DynamicComponents\Controls\Button('Ok!', [new EventManager(), 'click']);
// Trigger $btn click here
```
Successfully prints out "Clicked Ok!"

**Comment by WinterSilence** [comment]
@dmvdbrugge 
> Re 4: any error there is caused by whatever you do in that click

My mistake, don't saw this solution before
